spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gialam_clinic
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh
  mail:

    host: smtp.gmail.com

    port: 587

    username: khaiaodendeptrai@gmail.com

    password: nloa sldh fsft ioqj

    properties:

      mail:

        smtp:

          auth: true

          starttls:

            enable: true

app:

  verify-url:

    http://localhost:8080/api/v1/auth/verify

server:
  port: 8080

jwt:
  secret: your_super_secret_jwt_key_123456789123456789
  expiration: 86400000